name: mobile_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

  #---packages----#
dependencies:
  flutter:
    sdk: flutter
  # Utility Packages
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.1.0
  url_launcher: ^6.0.9
  flutter_native_splash: ^2.3.11
  smooth_page_indicator: ^1.1.0


  #---Icons----#
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6
  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1
#---end packages----#
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  #---Local Assets----#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/
    - assets/images/on_boarding_images/w1.gif
<<<<<<< HEAD
    - assets/images/on_boarding_images/pay.jpg
    - assets/images/on_boarding_images/deliver.jpg
=======
    - assets/images/on_boarding_images/w2.jpg
    - assets/images/animations/

>>>>>>> a98daafc7d7600f38628ba1987a6b88db39b9dae
  #---Local Fonts----#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets/logos/logo.png
  image_dark: assets/logos/logo.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#FFFFFF"
    image: assets/logos/logo.png
    image_dark: assets/logos/logo.png
    
  android_14:
    color: "#FFFFFF"
    color_dark: "#FFFFFF"
    image: assets/logos/logo.png
    image_dark: assets/logos/logo.png

  android_7:
    color: "#FFFFFF"
    color_dark: "#FFFFFF"
    image: assets/logos/logo.png
    image_dark: assets/logos/logo.png